---
- name: DotFiles Config
  hosts: localhost
  connection: local

  pre_tasks:
    - name: "Perform pre-tasks"
      ansible.builtin.import_tasks: pre_tasks/main.yml

  tasks:
    - name: "Set exclude roles"
      ansible.builtin.set_fact:
        ex_roles: "{{ exclude_roles }}"
      when: exclude_roles is defined

    - name: "Set roles"
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | community.general.lists_difference(ex_roles | default([])) }}"

    - name: "Display roles to be run"
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: "Run roles"
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ default_roles }}"
      tags:
        - always
