---
- name: "{{ role_name }} | install | redhat | Install dependencies with yum"
  ansible.builtin.yum:
    name: "{{ linuxbrew_install_dependencies }}"
    state: present
  when: linuxbrew_install_dependencies is defined
  become: true
